services:
#    api.example:
#        class: ApiBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
    api.ops.helper:
        class: ApiBundle\Service\OpsApiHelper
        arguments: ["@service_container", "@doctrine.orm.entity_manager"]