<?php

namespace ApiBundle\Repository;

/**
 * AllInfoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AllInfoRepository extends \Doctrine\ORM\EntityRepository
{
}
