<?php

namespace ApiBundle\Repository;

/**
 * CsmRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CsmRepository extends \Doctrine\ORM\EntityRepository
{
}
