<?php

namespace ApiBundle\Repository;

/**
 * OpsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OpsRepository extends \Doctrine\ORM\EntityRepository
{
}
